# Generated by Django 2.1.1 on 2018-09-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=100)),
                ('detail_url', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'banner1',
                'ordering': ['-bid'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('sub_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.Category')),
            ],
            options={
                'db_table': 'sub_menu',
            },
        ),
    ]
